### ISSUE TITLE
10 Representation

### ISSUE THREAD

**Issue by TexasHODL** [block52/poker-vm#1031]
10 is being shown as 1 in hand strength

<img width="1280" height="651" alt="Image" src="https://github.com/user-attachments/assets/8c29621b-b3d4-4ad6-98c8-c5b61f093f52" />

<img width="1280" height="641" alt="Image" src="https://github.com/user-attachments/assets/783e01d5-7786-4f9f-af43-4af4ef917a48" />

<img width="1280" height="650" alt="Image" src="https://github.com/user-attachments/assets/bb5b1af0-1413-4c3b-b0e4-18bea88f8eed" />

**Comment by TexasHODL** [comment]
Could be related to #1009

**Comment by bitcoinbrisbane** [comment]
Should be fixed on https://github.com/block52/poker-vm/pull/1032

**Comment by TexasHODL** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2fdf23ae-edac-40b1-ae36-93bec15badd4" />
10 Still being shown as 1

**Comment by TexasHODL** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a583e934-77df-4eb0-9be0-76cb226f992e" />
Still counting the 10 as 10 just not represented properly in hand strength.

**Comment by TexasHODL** [comment]
<img width="597" height="1280" alt="Image" src="https://github.com/user-attachments/assets/da1aaf5e-776a-4b03-a5f2-baf6c1f3cc02" />

<img width="597" height="1280" alt="Image" src="https://github.com/user-attachments/assets/1e24fab8-ead9-4101-817f-462cba609ec5" />

-10 still showing as 1
-New issue 10 card image no longer generating
